version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: news_app
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  laravel:
    image: laravel:latest
    container_name: laravel
    restart: unless-stopped
    build:
      context: ./laravel
      dockerfile: Dockerfile
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: news_app
      DB_USERNAME: root
      DB_PASSWORD: ""  # Ensure this is set to an empty string

  nextjs:
    image: node:18-alpine
    container_name: nextjs
    restart: unless-stopped
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    volumes:
      - ./nextjs:/usr/src/app
    ports:
      - "3000:3000"
    command: "npm run dev"
    depends_on:
      - laravel

volumes:
  mysql-data:
